### ISSUE TITLE
用html写标签有些标签功能不可用

### ISSUE THREAD

**Issue by moxiaobei2** [MeCKodo/wxapp-cli#3]
eg: `<pcontenteditable="true">这是一段可编辑的段落。请试着编辑该文本。</p>这里的可编辑属性，在编译过来之后就直接变成` `<p >这是一段可编辑的段落。请试着编辑该文本。</p>` 属性自动被吃掉了。

**Comment by MeCKodo** [comment]
这应该是微信不支持吧？。。不是编译的问题
