### ISSUE TITLE
npm run dev 命令不能及时编译文件

### ISSUE THREAD

**Issue by futantan** [MeCKodo/wxapp-cli#4]
一般情况下， `npm run dev` 命令能够很好的工作，但是在 scss 文件中，如果有 `@import`，而只修改了 import 的内容的话，是不会更新文件的，需要使用 `npm run build` 才可以。
例如：
> A.scss 文件 import B.scss 文件中的内容，只修改了 B 文件，微信 IDE 中不会及时更新。

另外，如果在 src 目录下删除了一些 scss 文件，微信 IDE 中也不会删除，希望能够在每次 bulid 的时候 clean 一次。

最后，感谢这么好用的工具！ Awesome！

**Comment by MeCKodo** [comment]
谢谢你的bug反馈以及建议。
我有空的时候看下哈

**Comment by MeCKodo** [comment]
修复了你说的不编译更新问题，也在build新增了clean  dist目录了

**Comment by futantan** [comment]
好像目前的工作方式不是特别适用。目前当当前页面的 wxml 文件有所改动的时候，整个项目都会重新编译，就跳转到了首页，还需要点击进入之前编辑的页面。之前是好的，希望能够解决一下，感谢。
